name: Wisla Tickets Watch (every 10 min)
on:
  schedule:
    - cron: "*/10 * * * *"   # co 10 minut (UTC)
  workflow_dispatch:

permissions:
  contents: write            # pozwól na commit z Actions

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          EVENT_ID: ${{ secrets.EVENT_ID }}   # ustawisz zaraz w Secrets
          OUTPUT_CSV: ticket_snapshots.csv
          ALERT_THRESHOLD: "1500"
        run: python scrape_wisla.py

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ticket_snapshots.csv
          git diff --quiet && echo "No changes" || (git commit -m "Update snapshots [skip ci]" && git push)
